import { writable } from "svelte/store";
import ControlState from "./state/control-state";
import DataState from "./state/data/data-state";
import FileState from "./state/file-state";
import InputState from "./state/input-state";
import PlaybackState from "./state/playback-state";
import TerminalState from "./state/terminal-state";
import DerivedState from "./state/derived-state";
import RefState from "./state/ref-state";
import SettingsState from "./state/settings-state";
import ToastState from "./state/toast-state";
import ConfirmDialogState from "./state/confirm-dialog-state";
import ActionMenuState from "./state/action-menu-state";
import FloatingTextInputState from "./state/floating-text-input-state";
import TrackManagerState from "./state/track-manager-state";
import AppErrorState from "./state/app-error-state";
import LibraryState from "./state/library-state";
import MappingState from "./state/mapping-state";

export const controlStore = writable<ControlState.Value>(ControlState.createInitial());
export const dataStore = writable<DataState.Value>(DataState.createInitial());
export const fileStore = writable<FileState.Value>(FileState.createInitial());
export const inputStore = writable<InputState.Value>(InputState.createInitial());
export const playbackStore = writable<PlaybackState.Value>(PlaybackState.createInitial());
export const terminalStore = writable<TerminalState.Value | null>(null);
export const derivedStore = writable<DerivedState.Value>(DerivedState.createInitial());
export const refStore = writable<RefState.Value>(RefState.createInitial());
export const settingsStore = writable<SettingsState.Value>(SettingsState.createInitial());
export const toastStore = writable<ToastState.Value | null>(null);
export const confirmDialogStore = writable<ConfirmDialogState.Value | null>(null);
export const actionMenuStore = writable<ActionMenuState.Value | null>(null);
export const floatingTextInputStore = writable<FloatingTextInputState.Value | null>(null);
export const trackManagerStore = writable<TrackManagerState.Value | null>(null);
export const appErrorStore = writable<AppErrorState.Value | null>(null);
export const libraryStore = writable<LibraryState.Value | null>(null);
export const mappingStore = writable<MappingState.Value | null>(null);
